# Generated by Django 4.0.1 on 2022-07-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
