# Generated by Django 4.0.3 on 2022-07-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_employee_gender_remove_employee_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('specification', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='teacher')),
            ],
        ),
    ]
